---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
data:
  CATALOGUE_HOST: "http://catalogue"
  REDIS_HOST: "redis"

---
apiVersion: v1
kind: Pod
metadata:
  name: cart
  labels:
    name: cart
    tire: app
spec:
  containers:
  - name: cart
    image: chaan2835/cart:k8
    envFrom:
    - configMapRef:
        name: cart-config
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    name: cart
    tire: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080