---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-config
data:
  CART_ENDPOINT: "cart"
  DB-HOST: "mysql"

---
apiVersion: v1
kind: Pod
metadata:
  name: shipping
  labels:
    name: shipping
    tire: app
spec:
  containers:
  - name: shipping
    image: chaan2835/shipping:k8
    envFrom:
    - configMapRef:
        name: shipping-config
    # resources:
    #   requests:
    #     cpu: "200m"
    #     memory: "256Mi"
    #   limits:
    #     cpu: "200m"
    #     memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  selector:
    name: shipping
    tire: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080