---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  MYSQL_DATABASE: "cities"
---
apiVersion: v1 
kind: Secret
metadata:
  name: mysql-mysecret
type: Opaque
data:
  username: c2hpcHBpbmc=
  password: c2VjcmV0
---
apiVersion: v1 
kind: Pod 
metadata:
  name: mysql
  labels:
    name: mysql 
    tire: db 
spec:
  containers:
  - name: mysql 
    imagePullPolicy: Always
    image: chaan2835/mysql:k8
    envFrom:
    - configMapRef:
        name: mysql-config 
    - secretRef:
        name: mysql-secret
    ports:
      - containerPort: 3306
    resouces:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
---
apiVersion: v1 
kind: Service
metadata:
  name: mysql 
spec:
  selector:
    name: mysql
    tire: db 
  ports:
    - protocol: TCP
      port: 80
      targetport: 3306