---
apiVersion: v1 
kind: Pod 
metadata:
  name: mysql
  labels:
    name: mysql 
    tire: db 
spec:
  containers:
  - name: mysql 
    imagePullPolicy: Always
    image: chaan2835/mysql:k8 
    ports:
      - containerPort: 3306
    resouces:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
---
apiVersion: v1 
kind: Service
metadata:
  name: mysql 
spec:
  selector:
    name: mysql
    tire: db 
  ports:
    - protocol: TCP
      port: 80
      targetport: 3306