---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
    tire: db
spec:
  containers:
  - name: mongodb
    image: chaan2835/mongodb:k8
	ports:
	- conatainerPort: 80 --> 2nd change added port defination and then delete and start the pod again then restart the catalogue too
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    name: mongodb
    tire: db
  ports:
    - protocol: TCP
      port: 80  #-->1st change changed to 80 
      targetPort: 27017