#creating a pod named as webpod
---
apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
    tire: frontend
spec:
  containers:
  - name: web
    imagePullPolicy: Always 
    image: chaan2835/web:k8
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
    ports:
      - containerPort: 80
---
#attaching a service to the pod using loadbalancer 
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector:
    name: web
    tire: frontend
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80 #target port is nothing but conatainer port